services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 5555:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis-service:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
