services:
  mongo-service:
    image: mongo
    restart: always
    ports:
      - 2717:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5555:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis-service:
    image: redis
    restart: always
    ports:
      - 6379:6379

  # Add orm configuration file for connectiong postgress...

  # postgres-service:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: app
  #     POSTGRES_DB: db

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 4444:8080
